### ISSUE TITLE
lavaanList convergence criteria for multilevel data

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#144]
Hi Yves,

When fitting a model to multilevel data (either a multilevel model, or simply cluster-robust *SE*s), `lavaanList()` says the model did not converge on any data sets, even though `lavaan()` converges on each data set.  

```
data(Demo.twolevel)
## create missing data
set.seed(123)
Demo.twolevel$y1[sample(nrow(Demo.twolevel), size = .1*nrow(Demo.twolevel)) ] <- NA
## impute missing data
library(mice)
m <- 5
mice.out <- mice(Demo.twolevel, m = m, diagnostics = TRUE)
imputedData <- list()
for (i in 1:m) {
  imputedData[[i]] <- complete(data = mice.out, action = i, include = FALSE)
}

model1 <- '
  fw =~ y1 + y2 + y3
  fw ~ x1 + x2 + x3
'
model2 <- '
level: within
  fw =~ y1 + y2 + y3
  fw ~ x1 + x2 + x3
level: between
  fb =~ y1 + y2 + y3
  fb ~ w1 + w2
'
sapply(imputedData, function(i) {
  fit1 <- sem(model1, data = i, cluster = "cluster")
  lavInspect(fit1, "converged")
}) # cluster-robust runs fine

sapply(imputedData, function(i) {
  fit2 <- sem(model2, data = i, cluster = "cluster")
  lavInspect(fit2, "converged")
}) # MLSEM runs fine

## both seem to fail in lavaanList()
semList(model1, dataList = imputedData, cluster = "cluster")
semList(model2, dataList = imputedData, cluster = "cluster")
```

I recall a past correspondence where you said the criteria might be set too strict for MLSEMs in `lavaanList()`, but I can't find a record.

**Comment by yrosseel** [comment]
I fixed another bug (the unintended creation of $cluster in @Options, because $clustered also existed), and as a side-effect, this solves this issue. Fixed in 0.6-4.

**Comment by TDJorgensen** [comment]
This still appears to be an issue when models have both multiple groups and multiple levels.

```
data(Demo.twolevel)
## assign clusters to arbitrary groups
Demo.twolevel$g <- ifelse(Demo.twolevel$cluster %% 2L, "foo", "bar")

model2 <- ' group: foo
level: within
  fw =~ y1 + L2*y2 + L3*y3
level: between
  fb =~ y1 + L2*y2 + L3*y3

group: bar

level: within
  fw =~ y1 + L2*y2 + L3*y3
level: between
  fb =~ y1 + L2*y2 + L3*y3
'

## converges fine
sem(model2, data = Demo.twolevel, cluster = "cluster", group = "g")
## but not according to lavaanList
semList(model2, dataList = list(Demo.twolevel, Demo.twolevel),
        cluster = "cluster", group = "g")
```
